{{- if and .Values.adotCollector.daemonSet.enabled .Values.adotCollector.daemonSet.serviceAccount.create -}}
# Service account provides identity information for a user to be able to authenticate processes running in a pod.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adotCollector.daemonSet.serviceAccount.name }}
  namespace: {{ include "adotCollector.daemonSet.namespace" . }}
  {{- with .Values.adotCollector.daemonSet.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
