{{- if .Values.adotCollector.daemonSet.enabled }}
# ConfigMap for ADOT Collector as a DaemonSet with the specified configurations, including configured values from values.yaml.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.adotCollector.daemonSet.configMap.name }}
  namespace: {{ .Values.adotCollector.daemonSet.namespace }}
  labels:
    app: {{ .Values.adotCollector.daemonSet.configMap.app }}
    component: {{ .Values.adotCollector.daemonSet.configMap.component }}
data:
  adot-config: |
    extensions:
      health_check: {{ .Values.adotCollector.daemonSet.extensions.healthCheck }}
    receivers:
      awscontainerinsightreceiver:
        collection_interval: {{ .Values.adotCollector.daemonSet.receivers.collectionInterval }}
        container_orchestrator: {{ .Values.adotCollector.daemonSet.receivers.containerOrchestrator }}
        add_service_as_attribute: {{ .Values.adotCollector.daemonSet.receivers.addServiceAsAttribute }}
        prefer_full_pod_name: {{ .Values.adotCollector.daemonSet.receivers.preferFullPodName }}
    processors:
      batch/metrics:
        timeout: {{ .Values.adotCollector.daemonSet.processors.timeout }}
      resourcedetection/k8s:
        detectors: [env]
        override: false
    exporters:
      datadog:
        api:
          key: "${DATADOG_INTERNAL_API_KEY}"
          site: {{ .Values.adotCollector.daemonSet.exporters.datadog.api.site }}
        metrics:
          resource_attributes_as_tags: {{ .Values.adotCollector.daemonSet.exporters.datadog.metrics.resource_attributes_as_tags }}
        use_resource_metadata: {{ .Values.adotCollector.daemonSet.exporters.datadog.use_resource_metadata }}
    service:
      pipelines:
        metrics:
          receivers: {{- range .Values.adotCollector.daemonSet.service.metrics.receivers }}
          - {{.}}{{- end }}
          processors: {{- range .Values.adotCollector.daemonSet.service.metrics.processors }}
          - {{.}}{{- end }}
          exporters: {{- range .Values.adotCollector.daemonSet.service.metrics.exporters }}
          - {{.}}{{- end }}
      extensions: {{- range .Values.adotCollector.daemonSet.service.extensions }}
      - {{.}}{{- end }}
{{- end }}
