{{- if .Values.fluentbit.enabled }}
# ClusterRole for Fluent Bit as a DaemonSet contains rules, and defines and grants permissions to specified resources/endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fluentbit.name }}
  labels:
    {{- include "aws-for-fluent-bit.labels" . | indent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
{{- end }}
