{{- if .Values.fluentbit.enabled }}
# Specify namespace for Fluent Bit.
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "aws-for-fluent-bit.namespace" . }}
  labels:
    name: {{ include "aws-for-fluent-bit.namespace" . }}
    {{- include "aws-for-fluent-bit.labels" . | indent 4 }}
{{- end }}
