{{- if .Values.fluentbit.enabled }}
# Service account provides identity information for a user to be able to authenticate processes running in a pod.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentbit.serviceAccount.name }}
  namespace: {{ include "aws-for-fluent-bit.namespace" . }}
  {{- with .Values.fluentbit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
